CREATE TABLE IF NOT EXISTS admins (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 active TINYINT NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS service_categories (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(160) NOT NULL,
 slug VARCHAR(160) NOT NULL UNIQUE,
 sort_order INT NOT NULL DEFAULT 0,
 active TINYINT NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX category_order (active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS services (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 category_id INT UNSIGNED NOT NULL,
 title VARCHAR(160) NOT NULL,
 slug VARCHAR(160) NOT NULL UNIQUE,
 short_description VARCHAR(500) NOT NULL,
 full_description TEXT NOT NULL,
 image VARCHAR(255) NOT NULL DEFAULT '',
 price_text VARCHAR(160) NOT NULL DEFAULT '',
 duration_text VARCHAR(160) NOT NULL DEFAULT '',
 featured TINYINT NOT NULL DEFAULT 0,
 active TINYINT NOT NULL DEFAULT 1,
 sort_order INT NOT NULL DEFAULT 0,
 seo_title VARCHAR(160) NOT NULL DEFAULT '',
 seo_description VARCHAR(300) NOT NULL DEFAULT '',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT service_category FOREIGN KEY (category_id) REFERENCES service_categories(id) ON DELETE RESTRICT,
 INDEX service_order (active, featured, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS gallery_items (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 image VARCHAR(255) NOT NULL,
 caption VARCHAR(160) NOT NULL DEFAULT '',
 alt_text VARCHAR(255) NOT NULL,
 featured TINYINT NOT NULL DEFAULT 1,
 active TINYINT NOT NULL DEFAULT 1,
 sort_order INT NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX gallery_order (active, featured, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS contact_requests (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(80) NOT NULL,
 phone VARCHAR(32) NOT NULL,
 email VARCHAR(120) NOT NULL DEFAULT '',
 service VARCHAR(160) NOT NULL,
 area VARCHAR(80) NOT NULL,
 message TEXT NOT NULL,
 status ENUM('new','in_progress','completed','spam') NOT NULL DEFAULT 'new',
 archived TINYINT NOT NULL DEFAULT 0,
 email_sent TINYINT NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX request_status (archived, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS site_settings (
 setting_key VARCHAR(80) PRIMARY KEY,
 setting_value TEXT NOT NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS request_photos (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 request_id INT UNSIGNED NOT NULL,
 filename VARCHAR(45) NOT NULL UNIQUE,
 width INT UNSIGNED NOT NULL,
 height INT UNSIGNED NOT NULL,
 bytes INT UNSIGNED NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT request_photo_request FOREIGN KEY (request_id) REFERENCES contact_requests(id) ON DELETE CASCADE,
 INDEX request_photo_order (request_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS reviews (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 request_id INT UNSIGNED NOT NULL UNIQUE,
 display_name VARCHAR(80) NOT NULL,
 rating TINYINT UNSIGNED NOT NULL,
 body VARCHAR(1500) NOT NULL,
 status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
 verified_at DATETIME NULL,
 published_at DATETIME NULL,
 moderated_by INT UNSIGNED NULL,
 moderated_at DATETIME NULL,
 moderation_note VARCHAR(500) NOT NULL DEFAULT '',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT review_request FOREIGN KEY (request_id) REFERENCES contact_requests(id) ON DELETE CASCADE,
 CONSTRAINT review_rating CHECK (rating BETWEEN 1 AND 5),
 INDEX review_publication (status,published_at,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS review_invitations (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 request_id INT UNSIGNED NOT NULL UNIQUE,
 token_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 expires_at DATETIME NOT NULL,
 used_at DATETIME NULL,
 revoked_at DATETIME NULL,
 mail_sent_at DATETIME NULL,
 created_by INT UNSIGNED NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT invitation_request FOREIGN KEY (request_id) REFERENCES contact_requests(id) ON DELETE CASCADE,
 CONSTRAINT invitation_admin FOREIGN KEY (created_by) REFERENCES admins(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
