CREATE TABLE IF NOT EXISTS review_invitations (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 request_id INT UNSIGNED NOT NULL UNIQUE,
 token_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 expires_at DATETIME NOT NULL,
 used_at DATETIME NULL,
 revoked_at DATETIME NULL,
 mail_sent_at DATETIME NULL,
 created_by INT UNSIGNED NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT invitation_request FOREIGN KEY (request_id) REFERENCES contact_requests(id) ON DELETE CASCADE,
 CONSTRAINT invitation_admin FOREIGN KEY (created_by) REFERENCES admins(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS moderated_by INT UNSIGNED NULL,
 ADD COLUMN IF NOT EXISTS moderated_at DATETIME NULL,
 ADD COLUMN IF NOT EXISTS moderation_note VARCHAR(500) NOT NULL DEFAULT '';
